config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :decks, only: [:new, :show, :create]

  resources :games, only: [:show] do
    post :draw
    post :shuffle
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  acts_as_list scope: :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_secure_token :share_token

  has_many :cards, -> { order(position: :asc) } do
    def shuffle!
      sql = ''
      pluck(:id).shuffle.each_with_index do |id, index|
        sql += "when (id=#{id}) then #{index + 1} "
      end
      sql = ['position=case', sql, 'end'].join(' ')
      update_all(sql)
    end
  end

  def draw
    drawn_card = cards.first
    drawn_card.delete
    drawn_card
  end
end

app/models/deck_form.rb
class DeckForm
  include ActiveModel::Model
  include Virtus.model

  attribute :name, String
  attribute :description, String
  attribute :cards, String

  attr_reader :deck

  def save
    if valid?
      persist!
      true
    else
      false
    end
  end

  def model
    @deck
  end

  private

  def persist!
    @deck = Deck.create!(name: name, description: description)
    cards.each_line.map do |card_name|
      @deck.cards << create_cards_from(card_name.chomp)
    end
  end

  def create_cards_from(card_name)
    if match = /^(\d+)x(.*)/.match(card_name)
      Array.new(match[1].to_i) do
        Card.new(name: match[2])
      end
    else
      Card.new(name: card_name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def new
    @deck = DeckForm.new
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def create
    @deck = DeckForm.new(deck_params)

    if @deck.valid?
      @deck.save
      @deck.model.cards.shuffle!
      redirect_to @deck.model, notice: "Deck was successfully created"
    else
      render 'new'
    end
  end

  private

  def deck_params
    params.require(:deck_form).permit(:name, :description, :cards)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @deck = Deck.find_by(share_token: params[:id])
  end

  def draw
    @deck = Deck.find_by(share_token: params[:game_id])
    @card = @deck.draw
    render :show
  end

  def shuffle
    @deck = Deck.find_by(share_token: params[:game_id])
    @deck.cards.shuffle!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decks/_deck_summary.html.erb
<h3 class="ui block header">Deck: <%= deck.name %></h3>
<p><%= deck.description %></p>
<p>Card count: <%= deck.cards.count %></p>

app/views/decks/new.html.erb
<h2>Create new deck</h2>

<%= form_for @deck, url: decks_path, html: { class: "ui form" } do |form| %>
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>
    <div class="field">
        <%= form.label :cards %>
        <%= form.text_area :cards %>
    </div>
    <div class="field">
        <%= form.submit class: "ui button" %>
    </div>
<% end %>

app/views/decks/show.html.erb
<%= render "deck_summary", deck: @deck %>
<%= link_to "Game link", game_path(@deck.share_token) %>

app/views/games/show.html.erb
<%= render "decks/deck_summary", deck: @deck %>

<div class="actions ui four column grid">
    <div class="row">
        <%= button_to "Draw card", 
            game_draw_path(@deck.share_token), 
            disabled: @deck.cards.empty?, 
            class: "ui button",
            form_class: "column" %>
        <%= button_to "Shuffle deck", game_shuffle_path(@deck.share_token), disabled: @deck.cards.empty?, class: "ui button" %>
    </div>
</div>

<% if @card.present? %>
    <hr/>
    <p>Card drawn: <%= @card.name %></p>
    <%= image_tag @card.name if Rails.application.assets.find_asset @card.name%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Thingofmanydecks</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="ui container">
            <h1 class="ui headers">Thing of many decks</h1>
            <% flash.each do |name, msg| -%>
                <div class="ui positive message">
                    <%= content_tag :p, msg %>
                </div>
            <% end -%>
            <%= yield %>
        </div>
    </body>
</html>